"""migration 2

Revision ID: 46a52d6c4630
Revises: f111dde6790b
Create Date: 2024-03-26 12:04:41.932682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46a52d6c4630'
down_revision: Union[str, None] = 'f111dde6790b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cvs', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cvs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now() + interval '1 day')"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cvs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('cvs', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
